baseURL = "https://ParkDyel.github.io/"
languageCode = "ko-kr"
title = "ParkDyel"
theme = "m10c"

[params]
  author = "ParkDyel"
  description = "용맹함을 가장한 무지함"
  avatar = "https://avatars1.githubusercontent.com/u/13329748?s=400&u=cba5ab6249e73518215f32d8a7427c116ce32f63&v=4"
  menu_item_separator = "/"
  [[params.social]]
    name = "github"
    url = "https://github.com/ParkDyel"
  [[params.social]]
    name = "mail"
    url = "dyel.sns@gmail.com"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
